### ISSUE TITLE
share

### ISSUE THREAD

**Issue by KongDeyu1532** [fabiopk/RT_GestureRecognition#1]
Hello, can you share the folder data in the configs file, thank you!

**Comment by fabiopk** [comment]
Do you mean the datasets?
The one used for the demo and for training from scratch is Jester.

The Jester dataset can be found here: https://20bn.com/datasets/jester
nvGesture: https://research.nvidia.com/publication/online-detection-and-classification-dynamic-hand-gestures-recurrent-3d-convolutional
EgoGesture: http://www.nlpr.ia.ac.cn/iva/yfzhang/datasets/egogesture.html

Let me know if that's what you needed.

Best, 
Fabio
