### ISSUE TITLE
Is Cuda indespenssible ?

### ISSUE THREAD

**Issue by Trutifruti** [fabiopk/RT_GestureRecognition#2]
Hi, I was wondering if I can run your programme without CUDA? I need to make an HMI on a not-so-great PC that doesn’t have the required hardware to work with CUDA.
I have been struggling to see how I need to modify your programme to rely solely on the CPU.
Thanks for everything !

**Comment by fabiopk** [comment]
Hi there,

I think you can run it without a GPU by removing every ".cuda()" piece of the code.
Of course, there will be some performance limitations by doing it this way.

Someone already ran this code using only the CPU, so you can have an idea of what you can expect in terms of performance https://www.youtube.com/watch?v=5vxY9YvVFOA.
Also, I think he made his code available, so you can check the modifications he did to make it run on a laptop without a GPU. 

Best of luck with your implementation. 
Let me know if have any other problem.

**Comment by Trutifruti** [comment]
awesome thanks so much for the tip !
